/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fundraisingSol from "./Fundraising.sol";
export { Crowdfunding__factory } from "./Fundraising__factory";
