/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fundraisingSol from "./Fundraising.sol";
export * as factories from "./factories/Fundraising.sol";
